### ISSUE TITLE
Add Instructions in readme for when android target fails to build

### ISSUE THREAD

**Issue by n0f3** [xamarin/dev-days-labs#11]
When getting the project fresh from Github and opening in Visual Studio, some users can get android build failures of type Unzipping failed for android_m2repository.

Add instructions in readme of lab to link to https://xamarinhelp.com/debugging-xamarin-android-build-and-deployment-failures/, which has a section on how to fix this problem.

**Comment by jamesmontemagno** [comment]
Will add in.
