### ISSUE TITLE
Latest update of xamarin for visual studio has build error on android

### ISSUE THREAD

**Issue by n0f3** [xamarin/dev-days-labs#12]
After updating to latest stable of xamarin, trying to compile android triggers this error: http://stackoverflow.com/questions/38222584/warning-major-version-52-is-newer-than-51-the-highest-major-version-supported-b. Installing version 1.8 of JDK, and having xamarin point to it fixed the issue.

Suggest to add some info about this in lab README

**Comment by jamesmontemagno** [comment]
Added it in to the readme
