### ISSUE TITLE
Build update for slides?

### ISSUE THREAD

**Issue by lothrop** [xamarin/dev-days-labs#28]
I was wondering if you're planning on an update for the slide decks after all the Build announcements?

**Comment by lextm** [comment]
A few things should be updated:

1. Visual Studio for Mac replaces Xamarin Studio.
2. Xamarin.Android supports AOT and hybrid.
3. Embedding.
4. Xamarin Live Player.

They upgrade the experience in so many ways :)

**Comment by brminnick** [comment]
Slides Updated ✅
